### PR TITLE
Compatibility with WP 6.2+ JS

### LINKED ISSUE #334: wp.editor.BlockControls is deprecated since version 5.3 and will be removed in version 6.2. Please use wp.blockEditor.BlockControls instead.
### Describe the bug

When adding the Brightcove block this warning is shown in WordPress 6.2.2

wp.editor.BlockControls is deprecated since version 5.3 and will be removed in version 6.2. Please use wp.blockEditor.BlockControls instead.

While the Block is still completely functional, we should update this asap to keep future compatibility. 

### Steps to Reproduce

* Insert Brightcove block
* Open developer tools
* See warning

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #335: wp.components.IconButton is deprecated since version 5.4 and will be removed in version 6.2. Please use wp.components.Button instead.
### Describe the bug

When adding the Brightcove block this warning is shown in WordPress 6.2.2

wp.components.IconButton is deprecated since version 5.4 and will be removed in version 6.2. Please use wp.components.Button instead.

While the Block is still completely functional, we should update this asap to keep future compatibility.

### Steps to Reproduce

* Insert Brightcove block
* Open developer tools
* See warning

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #336: Using custom components as toolbar controls is deprecated since version 5.6. Please use ToolbarItem, ToolbarButton or ToolbarDropdownMenu components instead
### Describe the bug

When adding the Brightcove block this warning is shown in WordPress 6.2.2

Using custom components as toolbar controls is deprecated since version 5.6. Please use ToolbarItem, ToolbarButton or ToolbarDropdownMenu components instead

While the Block is still completely functional, we should update this asap to keep future compatibility.

### Steps to Reproduce

* Insert Brightcove block
* Open developer tools
* See warning

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by felipeelia**
### Description of the Change

Closes #334
Closes #335
Closes #336

### Changelog Entry

> Changed - Use wp.blockEditor.BlockControls if available

### Credits

Props @felipeelia and @oscarssanchez 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

File: assets/js/src/block.js [hunk 1]
```diff
@@ -254,15 +256,19 @@
...
+						{
+							className:
+								'brightcove-add-media components-icon-button components-toolbar__control',
+							label: videoId.playlist_id
+								? __('Change Playlist', 'brightcove')
+								: __('Change Video', 'brightcove'),
+
+							'data-target': '#' + target,
+						},
+						el(Dashicon, { icon: 'edit' }),
```
Comment (felipeelia) [inline assets/js/src/block.js:270]: Added it as the component content because the `icon` attribute was not available in WP 5.2.

File: assets/js/src/block.js [hunk 2]
```diff
@@ -1,12 +1,14 @@
 /* global wp, bctiny, bcBlock */
-(function (blocks, element, components, editor) {
+(function (blocks, element, components) {
 	const { __, sprintf } = wp.i18n;
 
+	const { blockEditor, editor } = wp;
+	const BlockControls = blockEditor.BlockControls || editor.BlockControls;
```
Comment (JakePT) [inline assets/js/src/block.js:6]: @felipeelia If `blockEditor` doesn't exist then I believe this will throw an error, so it would never be able to fall back to `editor.blockControls`. According to the error message `editor.blockControls` was deprecated in 5.3, so it's been around at least that long. It looks like the plugin needs to support 4.2+ so you would need to check whether it exists in 4.2. If it does, the fallback to `editor` isn't needed, otherwise the error will need to be corrected.

One option is to just use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining):

```
const { blockEditor, editor } = wp;
const BlockControls = blockEditor?.BlockControls || editor.BlockControls;
```

But unless there is a build process with Babel this won't work on some older browsers (versions from early 2020).

For a bit better support (early 2018 versions) you could define some defaults when [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment):

```
const { blockEditor = {}, editor = {} } = wp;
const BlockControls = blockEditor.BlockControls || editor.BlockControls;
```

This way, since `blockEditor` will at least be an empty object, `blockEditor.BlockControls` won't throw an error if it doesn't exits.

**Review by JakePT — CHANGES_REQUESTED** [review]

File: assets/js/src/block.js (hunk 2 above)
Comment (felipeelia) [reply assets/js/src/block.js:6]: @JakePT good point, thanks. The code already relies on the fact that wp.blockEditor exists, when it calls `InspectorControls = wp.blockEditor.InspectorControls` down a couple of lines. In fact, it seems the plugin is already incompatible with WP 5.1 and older.

**Review by JakePT — APPROVED** [review]
