### PR TITLE
Fix: Only variables should be passed by reference

### LINKED ISSUE #357: Notice: Only variables should be passed by reference
### Describe the bug

The edit label page throws this warning .

```

Notice | Only variables should be passed by reference | +wp-content/plugins/brightcove-video-connect/includes/admin/class-bc-admin-labels-page.php:55


```

### Steps to Reproduce

1. Go to the Label page
2. Edit the label

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by MARQAS**
### Description of the Change
This PR fixes an issue where the plugin throws a warning in the label field while editing a label

Closes #357 

### How to test the Change

1. Go to the Labels page
2. Click on Edit label
3. It should display the label value

### Changelog Entry

> Fixed - PHP warning while editing a label

### Credits

Props @MARQAS , @felipeelia

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/admin/class-bc-admin-labels-page.php [hunk 1]
```diff
@@ -52,7 +52,7 @@ public function render_edit_label_page() {
 						<tr class="form-field form-required term-name-wrap">
 							<th scope="row"><label for="name">Label</label></th>
 							<td>
-								<input name="label-update" id="name" type="text" value="<?php echo esc_attr( end( array_filter( explode( '/', $_GET['update_label'] ) ) ) ); ?>" size="40" aria-required="true"> <?php // phpcs:ignore WordPress.Security.NonceVerification ?>
+								<input name="label-update" id="name" type="text" value="<?php echo esc_attr( basename( trim( $_GET['update_label'], '/' ) ) ); ?>" size="40" aria-required="true"> <?php // phpcs:ignore WordPress.Security.NonceVerification ?>
```
Comment (felipeelia) [inline includes/admin/class-bc-admin-labels-page.php:55]: Wouldn't it be better to assign its value to a variable anyway, @MARQAS? What if $_GET['update_label'] is not set?

File: includes/admin/class-bc-admin-labels-page.php [hunk 2]
```diff
@@ -46,13 +47,13 @@ public function render_edit_label_page() {
...
-				<input type="hidden" name="label-path" value="<?php echo ! empty( $_GET['update_label'] ) ? esc_attr( $_GET['update_label'] ) : ''; // phpcs:ignore ?>">
+				<input type="hidden" name="label-path" value="<?php echo esc_attr( $label_name ); ?>">
 				<table class="form-table">
 					<tbody>
 						<tr class="form-field form-required term-name-wrap">
-							<th scope="row"><label for="name">Label</label></th>
+							<th scope="row"><label for="name"><?php esc_html_e( 'Label', 'brightcove' ); ?></label></th>
 							<td>
-								<input name="label-update" id="name" type="text" value="<?php echo esc_attr( end( array_filter( explode( '/', $_GET['update_label'] ) ) ) ); ?>" size="40" aria-required="true"> <?php // phpcs:ignore WordPress.Security.NonceVerification ?>
+								<input name="label-update" id="name" type="text" value="<?php echo esc_attr( basename( trim( $label_name, '/' ) ) ); ?>" size="40" aria-required="true"> <?php // phpcs:ignore WordPress.Security.NonceVerification ?>
```
Comment (felipeelia) [inline includes/admin/class-bc-admin-labels-page.php:56]:
```suggestion
								<input name="label-update" id="name" type="text" value="<?php echo esc_attr( basename( trim( $label_name, '/' ) ) ); ?>" size="40" aria-required="true">
```

**Review by felipeelia — CHANGES_REQUESTED** [review]

**Review by felipeelia — APPROVED** [review]
